export default {
    THEME_CHANGED: "THEME_CHANGED",
    THEME_INIT: "THEME_INIT",
    POPULAR_REFRESH: "POPULAR_REFRESH",
    LOAD_POPULAR_FAIL: "LOAD_POPULAR_FAIL",
    LOAD_POPULAR_SUCCESS: "LOAD_POPULAR_SUCCESS"
};