export default {
    EVENT_TYPE_TIME_SPAN_CHANGED: 'EVENT_TYPE_TIME_SPAN_CHANGED',
    EVENT_TYPE_TAB_SELECT_CHANGE: 'EVENT_TYPE_TAB_SELECT_CHANGE',
    EVENT_TYPE_POPULAR_FAVORITE_CHANGE: 'EVENT_TYPE_POPULAR_FAVORITE_CHANGE',
    EVENT_TYPE_TRENDING_FAVORITE_CHANGE: 'EVENT_TYPE_TRENDING_FAVORITE_CHANGE',
};
